# Generated by Django 4.2 on 2023-05-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
